// resources/assets/components/MapViewer/MapViewer.tsx
import React, { memo, useCallback, useState } from 'react';
import { GoogleMap, useJsApiLoader } from '@react-google-maps/api';
import styles from './MapViewer.scss';
import mapStyle from './mapStyle';

const center = {
    lat: 52,
    lng: 20
};

const MapViewer: React.FC = () => {
    const { isLoaded } = useJsApiLoader({
        id: 'google-map-script',
        googleMapsApiKey: 'AIzaSyCi0sAXQWFeT4T5E6jOLlD-V35S6nyrx5Y'
    });

    const [map, setMap] = useState(null);

    const onLoad = useCallback((map) => {
        // const bounds = new window.google.maps.LatLngBounds();
        // map.fitBounds(bounds);
        setMap(map);
    }, []);

    const onUnmount = useCallback((map) => {
        setMap(null);
    }, []);

    return isLoaded ? (
        <div className={styles.mapViewer}>
            <GoogleMap
                mapContainerStyle={{ width: '100%', height: '100%' }}
                center={center}
                zoom={6}
                onLoad={onLoad}
                onUnmount={onUnmount}
                options={{ disableDefaultUI: true, styles: mapStyle }}
            >
                { /* Child components, such as markers, info windows, etc. */}
                <></>
            </GoogleMap>
        </div>
    ) : <></>;
};

export default memo(MapViewer);

// resources/assets/components/MapViewer.vue
<style lang="scss" scoped>
@import '@/styles/bootstrap.scss';

.mapViewer {
    @extend %right-column;

    @include respond-to(null, 'lg') {
        display: none;
    }

    border-radius: 15px;
    overflow: hidden;
    flex: auto;
    border: 1px solid #29292e;
    background-color: #29292e;
}
</style>

<template>
    <div class=mapViewer>
        <GoogleMap
            api-key="AIzaSyCi0sAXQWFeT4T5E6jOLlD-V35S6nyrx5Y"
            style="width: 100%; height: 100%"
            :center="center"
            :zoom="6"
        >
        </GoogleMap>
    </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import { GoogleMap, Marker } from "vue3-google-map";

export default defineComponent({
    components: { GoogleMap, Marker },
    setup() {
        const center = { lat: 52, lng: 20 };

        return { center };
    },
});
</script>
